paths:
  'jquery': 'jquery/jquery'
  'jqery-ujs': 'jquery-ujs/src/rails'
  'bootstrap-dropdown': 'twitter/bootstrap/bootstrap-dropdown'
  'bootstrap-modal': 'twitter/bootstrap/bootstrap-modal'
  'handlebars': 'handlebars'
  'typeahead': 'typeahead.js/dist/typeahead'
  'underscore': 'underscore/underscore'
  'd3': 'd3/d3'
baseUrl: 'assets'
